/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ecole;

import java.awt.Color;
import java.math.BigDecimal;
import java.sql.*;
import java.util.HashMap;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

import org.jfree.chart.*;
import org.jfree.chart.plot.CategoryPlot;
import org.jfree.chart.plot.PlotOrientation;
import org.jfree.data.category.DefaultCategoryDataset;


/**
 *
 * @author Atar EL AZIZ
 */
public class Gestion_des_notes extends javax.swing.JFrame {

    /**
     * Creates new form Gestion_des_notes
     */
    Connexion conn = new Connexion();
    Statement stm;
    ResultSet Rs;
    DefaultTableModel model= new DefaultTableModel();
    public Gestion_des_notes() {
        initComponents();
        
        model.addColumn("id");
        model.addColumn("nom");
        model.addColumn("prenom");
        model.addColumn("branche");
        model.addColumn("note");
        
        //La connection à la base de donnée
        try{
        stm = conn.obtenirConnexion().createStatement();
        ResultSet Rs= stm.executeQuery("Select * from etudiant");
        while(Rs.next()){
        model.addRow(new Object[] {Rs.getString("id"),Rs.getString("Nom"),Rs.getString("Prenom"),
        Rs.getString("branche"),Rs.getString("note")});
        }
        }catch(Exception e){System.err.println(e);}
        
        tble.setModel(model);
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    
    //methode pour afficher le text selectionné dans les cases
    private void deplace(int i){
    try{
    txtid.setText(model.getValueAt(i,0).toString());
    txtnom.setText(model.getValueAt(i,1).toString());
    txtprenom.setText(model.getValueAt(i,2).toString());
    txtbr.setSelectedItem(model.getValueAt(i,3).toString());
    txtnote.setText(model.getValueAt(i,4).toString());
    }catch (Exception e){System.err.println(e);
    JOptionPane.showMessageDialog(null, "erreur de deplacement"+e.getLocalizedMessage());}
    }
    
    //la méthode qui sert a afficher les informations dans les cases à chaque actualisation 
    private void afficher(){
    try{
            model.setRowCount(0);
        stm = conn.obtenirConnexion().createStatement();
        ResultSet Rs= stm.executeQuery("Select * from etudiant");
        while(Rs.next()){
            model.addRow(new Object[] {Rs.getString("id"),Rs.getString("Nom"),Rs.getString("Prenom"),
                Rs.getString("branche"),Rs.getString("note")});
        }
        }catch(Exception e){System.err.println(e);}
        
        tble.setModel(model);
    }
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton11 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jButton13 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        txtrecherche = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jButton14 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        txtid = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        txtprenom = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtbr = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        txtnote = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtnom = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tble = new javax.swing.JTable();
        jLabel9 = new javax.swing.JLabel();

        jButton11.setText("jButton11");

        jButton10.setText("jButton10");

        jButton13.setText("jButton13");

        jButton12.setText("jButton12");

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ecole/icons/blanc.jpg"))); // NOI18N
        jLabel7.setText("jLabel7");

        jButton1.setText("jButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(500, 600));
        getContentPane().setLayout(null);

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ecole/icons/add-administrator.png"))); // NOI18N
        jButton2.setText("Ajouter");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(40, 370, 153, 50);

        jButton3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ecole/icons/icons8-change-user-24.png"))); // NOI18N
        jButton3.setText("Modifier");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(410, 370, 150, 50);

        jButton4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ecole/icons/icons8-cancel-48.png"))); // NOI18N
        jButton4.setText("Supprimer");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4);
        jButton4.setBounds(590, 370, 160, 50);

        jButton5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ecole/icons/icons8-update-50.png"))); // NOI18N
        jButton5.setText("Actualiser");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5);
        jButton5.setBounds(220, 370, 160, 50);

        jButton7.setBackground(new java.awt.Color(204, 204, 255));
        jButton7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ecole/icons/icons8-search-24.png"))); // NOI18N
        jButton7.setText("recherche");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton7);
        jButton7.setBounds(230, 460, 140, 40);

        txtrecherche.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtrecherche.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtrechercheActionPerformed(evt);
            }
        });
        getContentPane().add(txtrecherche);
        txtrecherche.setBounds(380, 460, 120, 40);

        jLabel6.setFont(new java.awt.Font("Times New Roman", 3, 48)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(204, 204, 255));
        jLabel6.setText("Gestion des notes");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(150, 20, 400, 50);

        jButton14.setText("HISTO");
        jButton14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton14ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton14);
        jButton14.setBounds(650, 310, 120, 23);

        jButton8.setBackground(new java.awt.Color(204, 204, 255));
        jButton8.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jButton8.setText("Menu Principale");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton8);
        jButton8.setBounds(643, 10, 140, 50);

        txtid.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtidActionPerformed(evt);
            }
        });
        getContentPane().add(txtid);
        txtid.setBounds(160, 110, 110, 30);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("id :");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(90, 110, 40, 20);

        txtprenom.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtprenom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtprenomActionPerformed(evt);
            }
        });
        getContentPane().add(txtprenom);
        txtprenom.setBounds(160, 190, 110, 30);

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Prenom :");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(90, 200, 66, 17);

        txtbr.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "INFO ", "Physique", "Maths", " " }));
        getContentPane().add(txtbr);
        txtbr.setBounds(160, 240, 110, 20);

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Branche:");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(90, 240, 66, 17);

        txtnote.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtnote.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnoteActionPerformed(evt);
            }
        });
        getContentPane().add(txtnote);
        txtnote.setBounds(160, 280, 110, 30);

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Note:");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(90, 290, 33, 17);

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Nom :");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(90, 160, 40, 17);

        txtnom.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtnom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnomActionPerformed(evt);
            }
        });
        getContentPane().add(txtnom);
        txtnom.setBounds(160, 150, 110, 30);

        tble.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "ID", "Nom", "Prenom", "Matiére", "Note"
            }
        ));
        tble.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbleMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tble);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(360, 130, 410, 157);

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ecole/icons/gestion.jpg"))); // NOI18N
        getContentPane().add(jLabel9);
        jLabel9.setBounds(0, 0, 800, 510);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtidActionPerformed

    //la méthode pour ajouter un etudiant à la base de donnée 
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        String id=txtid.getText();
        String nom=txtnom.getText();
        String prenom=txtprenom.getText();
        String branche=txtbr.getSelectedItem().toString();
        String note=txtnote.getText();
        String requete1 = "select * from etudiant where Nom ='"+nom+"' and Prenom='"+prenom+"' and branche='"+branche+"'";
        String requete = "insert into etudiant(id, Nom, Prenom, branche, note)VALUES('"+
                id+"','"+nom+"','"+prenom+"','"+branche+"','"+note+"')";
        try{
            
            
            model.setRowCount(0);//pour vider la liste des etudiants
        
            ResultSet result = stm.executeQuery(requete1);
        if (result.next()){
            JOptionPane.showMessageDialog(null, "l'etudiant existe");
        } else {
            stm.executeUpdate(requete);
           JOptionPane.showMessageDialog(null, "l'etudiant est bien ajouter");
           txtnom.setText("");
           txtprenom.setText("");
           txtbr.setSelectedItem(2);
           txtnote.setText("");   
        }
            
        
        afficher();
       
        
        }catch(Exception ex){JOptionPane.showMessageDialog(null,"l'id est déja attribué"+ex.getMessage());}
        
        
    }//GEN-LAST:event_jButton2ActionPerformed

    //la méthode pour modifier les information d'un etudiant
    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        try{
        if(JOptionPane.showConfirmDialog(null, "Confirmer la modification", "modification",
                JOptionPane.YES_NO_OPTION) == JOptionPane.OK_OPTION){
        stm.executeUpdate("UPDATE etudiant SET Nom='"+txtnom.getText()+"',Prenom='"+txtprenom.getText()+
                "',branche='"+txtbr.getSelectedItem().toString()+"',note='"+txtnote.getText()+
                "' WHERE id= "+txtid.getText());
                afficher();
        }
        }catch (Exception e){JOptionPane.showMessageDialog(null,"erreur de Modification !!!!"+e.getMessage());
        System.err.println(e);}
    }//GEN-LAST:event_jButton3ActionPerformed
        
    //Modification de l'action du Bouton Supprimer
    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        try{
        if(JOptionPane.showConfirmDialog(null, "Attention ! Vous allez supprimer un etudiant, est ce que vous etes sure?",
                "Suprimmer Etudiant", JOptionPane.YES_NO_OPTION)==JOptionPane.OK_OPTION)
            if(txtid.getText().length() !=0){
            stm.executeUpdate("Delete From etudiant where id= "+txtid.getText());
            afficher();
            }
            else {JOptionPane.showMessageDialog(null, "veuillez remplire le champ id !");}
        }catch(Exception e){JOptionPane.showMessageDialog(null, "Erreur de suppression\n"+e.getMessage());}
        
    }//GEN-LAST:event_jButton4ActionPerformed

    //la methode pour actualiser
    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        afficher();
    }//GEN-LAST:event_jButton5ActionPerformed
           
    //Methode pour faire la recherche
    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
        try{
        model.setRowCount(0);//pour vider la liste des etudiants
        {
            Rs = stm.executeQuery("Select * From etudiant where Nom = '"+txtrecherche.getText()+"'");
        }while (Rs.next()){
        Object [] etudiant={Rs.getInt(1),Rs.getString(2),Rs.getString(3),Rs.getString(4),Rs.getInt(5)};
        model.addRow(etudiant);
        }if(model.getRowCount()==0){JOptionPane.showMessageDialog(null, "il y a aucun etudiant");
        }else {int i=0;
        deplace(i);
        }
        }catch (Exception e){System.err.println(e);
        JOptionPane.showMessageDialog(null,e.getMessage());
        }
    }//GEN-LAST:event_jButton7ActionPerformed

    private void tbleMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbleMouseClicked
        // TODO add your handling code here:
        try{
        int i=tble.getSelectedRow();deplace(i);
        }catch(Exception e){JOptionPane.showMessageDialog(null, "erreur de deplacement"+e.getLocalizedMessage());}
    }//GEN-LAST:event_tbleMouseClicked

    private void txtrechercheActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtrechercheActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtrechercheActionPerformed

    private void jButton14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton14ActionPerformed
        
        
       DefaultCategoryDataset dataset=new DefaultCategoryDataset();
       HashMap<String,Integer> noteEleves = new HashMap<String,Integer>();
       noteEleves.put("Aya", 10);
       noteEleves.put("Segado", 20);
       noteEleves.put("Atar", 12);
       noteEleves.put("Nasser", 22);
       noteEleves.forEach((k,v) -> dataset.setValue(v, "Marks", k));
        //dataset.setValue(90, "Marks", "Student4");
        JFreeChart chart = ChartFactory.createBarChart("Student score", "student name", "Marks", dataset, PlotOrientation.VERTICAL, false, true, false);
        CategoryPlot p = chart.getCategoryPlot();
        p.setRangeGridlinePaint(Color.black);
        ChartFrame frame = new ChartFrame("Bar Chart for student", chart);
        frame.setVisible(true);
        frame.setSize(450,350);
        
    }//GEN-LAST:event_jButton14ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:
         PrincipaleProf prin =new PrincipaleProf();
        this.setVisible(false);
        prin.setVisible(true);
    }//GEN-LAST:event_jButton8ActionPerformed

    private void txtprenomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtprenomActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtprenomActionPerformed

    private void txtnoteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnoteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnoteActionPerformed

    private void txtnomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnomActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnomActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Gestion_des_notes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Gestion_des_notes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Gestion_des_notes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Gestion_des_notes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Gestion_des_notes().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tble;
    private javax.swing.JComboBox<String> txtbr;
    private javax.swing.JTextField txtid;
    private javax.swing.JTextField txtnom;
    private javax.swing.JTextField txtnote;
    private javax.swing.JTextField txtprenom;
    private javax.swing.JTextField txtrecherche;
    // End of variables declaration//GEN-END:variables
}
