/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ecole;

import java.math.BigDecimal;
import java.sql.*;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Atar EL AZIZ
 */
public class Inscription extends javax.swing.JFrame {

    /**
     * Creates new form Inscription
     */
    Connexion conn = new Connexion();
    Statement stm;
    ResultSet Rs;
    
    public Inscription() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtad = new javax.swing.JTextPane();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtnom = new javax.swing.JTextPane();
        jScrollPane3 = new javax.swing.JScrollPane();
        txttel = new javax.swing.JTextPane();
        jScrollPane4 = new javax.swing.JScrollPane();
        txtprenom = new javax.swing.JTextPane();
        jScrollPane5 = new javax.swing.JScrollPane();
        txtniv = new javax.swing.JTextPane();
        jButton1 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane6 = new javax.swing.JScrollPane();
        txtdebut = new javax.swing.JTextPane();
        jButton2 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(700, 510));
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 3, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Inscrire un étudiant");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(90, 30, 350, 42);

        jLabel2.setFont(new java.awt.Font("Traditional Arabic", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Prenom :");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(80, 190, 110, 20);

        jLabel3.setFont(new java.awt.Font("Traditional Arabic", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Adresse :");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(80, 230, 110, 20);

        jLabel4.setFont(new java.awt.Font("Traditional Arabic", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Nom :");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(80, 140, 110, 20);

        jLabel5.setFont(new java.awt.Font("Traditional Arabic", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Niveau : ");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(80, 360, 110, 20);

        jLabel6.setFont(new java.awt.Font("Traditional Arabic", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Telephone :");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(80, 270, 110, 20);

        jScrollPane1.setViewportView(txtad);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(210, 220, 143, 30);

        jScrollPane2.setViewportView(txtnom);

        getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(210, 130, 143, 30);

        jScrollPane3.setViewportView(txttel);

        getContentPane().add(jScrollPane3);
        jScrollPane3.setBounds(210, 270, 143, 30);

        jScrollPane4.setViewportView(txtprenom);

        getContentPane().add(jScrollPane4);
        jScrollPane4.setBounds(210, 180, 143, 30);

        jScrollPane5.setViewportView(txtniv);

        getContentPane().add(jScrollPane5);
        jScrollPane5.setBounds(210, 350, 143, 30);

        jButton1.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jButton1.setText("Inscription");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(210, 410, 146, 41);

        jLabel7.setFont(new java.awt.Font("Traditional Arabic", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Inscrit(e) le :");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(80, 320, 110, 20);

        jScrollPane6.setViewportView(txtdebut);

        getContentPane().add(jScrollPane6);
        jScrollPane6.setBounds(210, 310, 143, 30);

        jButton2.setText("Menu Principale");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(650, 0, 137, 50);

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ecole/icons/inscri.png"))); // NOI18N
        getContentPane().add(jLabel9);
        jLabel9.setBounds(480, 60, 230, 430);

        jLabel8.setFont(new java.awt.Font("Traditional Arabic", 1, 18)); // NOI18N
        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ecole/icons/iscri.jpg"))); // NOI18N
        getContentPane().add(jLabel8);
        jLabel8.setBounds(0, 0, 800, 530);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
         String nom=txtnom.getText();
         String prenom=txtprenom.getText();
         String adresse=txtad.getText();
        String tel=txttel.getText();
        String debut=txtdebut.getText();
        String niveau = txtniv.getText();
        
        String requete1 = "select * from etudiant where Nom ='"+nom+"' and Prenom='"+prenom+"' and adresse='"+adresse+"'";
        String requete = "insert into etudiant(Nom, Prenom, adresse, tel, debut, niveau)VALUES('"+
                nom+"','"+prenom+"','"+adresse+"','"+tel+"','"+debut+"','"+niveau+"')";
        
        try{
            stm = conn.obtenirConnexion().createStatement();
            
        
            ResultSet result = stm.executeQuery(requete1);
        if (result.next()){
            JOptionPane.showMessageDialog(null, "l'etudiant existe");
        } else {
            stm.executeUpdate(requete);
           JOptionPane.showMessageDialog(null, "l'etudiant est bien ajouter");
           txtnom.setText("");
           txtprenom.setText("");
           txtad.setText("");
           txttel.setText(""); 
           txtdebut.setText("");
           txtniv.setText("");
        }
            
        }catch(Exception ex){JOptionPane.showMessageDialog(null,ex.getMessage());}
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
         PrincipaleProf prin =new PrincipaleProf();
        this.setVisible(false);
        prin.setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Inscription.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Inscription.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Inscription.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Inscription.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Inscription().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JTextPane txtad;
    private javax.swing.JTextPane txtdebut;
    private javax.swing.JTextPane txtniv;
    private javax.swing.JTextPane txtnom;
    private javax.swing.JTextPane txtprenom;
    private javax.swing.JTextPane txttel;
    // End of variables declaration//GEN-END:variables
}
