/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ecole;

import java.awt.Color;
import java.math.BigDecimal;
import java.sql.*;

import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Atar EL AZIZ
 */
public class Professeur extends javax.swing.JFrame {

    Connexion conn = new Connexion();
    Statement stm;
    ResultSet Rs;
    DefaultTableModel model= new DefaultTableModel();
    
    public Professeur() {
        initComponents();
        
        model.addColumn("id");
        model.addColumn("nom");
        model.addColumn("prenom");
        model.addColumn("matiere");
        model.addColumn("niveau");
        model.addColumn("dateDebut");
        
        //La connection à la base de donnée
        try{
        stm = conn.obtenirConnexion().createStatement();
        Rs= stm.executeQuery("Select * from professeur");
        while(Rs.next()){
        model.addRow(new Object[] {Rs.getString("id"),Rs.getString("Nom"),Rs.getString("Prenom"),
        Rs.getString("matiere"),Rs.getString("niveau"),Rs.getString("start")});
        }
        }catch(Exception e){System.err.println(e);}
        
        tble.setModel(model);
        
    }
    
    //methode pour afficher le text selectionné dans les cases
    private void deplace(int i){
    try{
    txtid.setText(model.getValueAt(i,0).toString());
    txtnom.setText(model.getValueAt(i,1).toString());
    txtprenom.setText(model.getValueAt(i,2).toString());
    txtmatiere.setText(model.getValueAt(i,3).toString());
    txtniv.setText(model.getValueAt(i,4).toString());
    txtstart.setText(model.getValueAt(i,5).toString());
    }catch (Exception e){System.err.println(e);
    JOptionPane.showMessageDialog(null, "erreur de deplacement"+e.getLocalizedMessage());}
    }
    
    //la méthode qui sert a afficher les informations dans les cases à chaque actualisation 
    private void afficher(){
    try{
            model.setRowCount(0);
        stm = conn.obtenirConnexion().createStatement();
        Rs= stm.executeQuery("Select * from professeur");
        while(Rs.next()){
            model.addRow(new Object[] {Rs.getString("id"),Rs.getString("Nom"),Rs.getString("Prenom"),
                Rs.getString("matiere"),Rs.getString("niveau"),Rs.getString("start")});
        }
        }catch(Exception e){System.err.println(e);}
        
        tble.setModel(model);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tble = new javax.swing.JTable();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtprenom = new javax.swing.JTextPane();
        jScrollPane3 = new javax.swing.JScrollPane();
        txtmatiere = new javax.swing.JTextPane();
        jScrollPane4 = new javax.swing.JScrollPane();
        txtniv = new javax.swing.JTextPane();
        jScrollPane5 = new javax.swing.JScrollPane();
        txtstart = new javax.swing.JTextPane();
        jScrollPane6 = new javax.swing.JScrollPane();
        txtnom = new javax.swing.JTextPane();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane7 = new javax.swing.JScrollPane();
        txtid = new javax.swing.JTextPane();
        jLabel9 = new javax.swing.JLabel();
        jButton6 = new javax.swing.JButton();
        jScrollPane8 = new javax.swing.JScrollPane();
        txtrecherche = new javax.swing.JTextPane();
        jLabel7 = new javax.swing.JLabel();

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(760, 530));
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 3, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 204, 255));
        jLabel1.setText("Gestion des professeurs");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(140, 80, 510, 59);

        jButton1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jButton1.setText("Menu Principale");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(596, 11, 133, 51);

        tble.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Nom", "Prenom", "Matiere", "Niveau enseigné", "Date de début"
            }
        ));
        tble.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbleMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tble);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(105, 155, 586, 121);

        jButton2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ecole/icons/icons8-change-user-24.png"))); // NOI18N
        jButton2.setText("Modifier");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(224, 368, 143, 52);

        jButton3.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ecole/icons/icons8-update-50.png"))); // NOI18N
        jButton3.setText("Actualiser");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(401, 368, 147, 52);

        jButton4.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ecole/icons/icons8-cancel-48.png"))); // NOI18N
        jButton4.setText("Supprimer");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4);
        jButton4.setBounds(577, 368, 151, 52);

        jButton5.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ecole/icons/add-administrator.png"))); // NOI18N
        jButton5.setText("Ajouter");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5);
        jButton5.setBounds(52, 368, 154, 52);

        jScrollPane2.setViewportView(txtprenom);

        getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(240, 320, 119, 31);

        jScrollPane3.setViewportView(txtmatiere);

        getContentPane().add(jScrollPane3);
        jScrollPane3.setBounds(370, 320, 119, 31);

        jScrollPane4.setViewportView(txtniv);

        getContentPane().add(jScrollPane4);
        jScrollPane4.setBounds(500, 320, 119, 31);

        jScrollPane5.setViewportView(txtstart);

        getContentPane().add(jScrollPane5);
        jScrollPane5.setBounds(630, 320, 119, 31);

        jScrollPane6.setViewportView(txtnom);

        getContentPane().add(jScrollPane6);
        jScrollPane6.setBounds(110, 320, 119, 31);

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(204, 204, 255));
        jLabel2.setText("Prenom");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(280, 300, 40, 15);

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(204, 204, 255));
        jLabel3.setText("ID");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(40, 300, 14, 15);

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(204, 204, 255));
        jLabel4.setText("Matiére");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(410, 300, 39, 15);

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(204, 204, 255));
        jLabel5.setText("Date de début");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(650, 300, 72, 20);

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(204, 204, 255));
        jLabel6.setText("Niveau");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(540, 300, 36, 15);

        jScrollPane7.setViewportView(txtid);

        getContentPane().add(jScrollPane7);
        jScrollPane7.setBounds(30, 320, 50, 30);

        jLabel9.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(204, 204, 255));
        jLabel9.setText("Nom");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(160, 300, 30, 20);

        jButton6.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ecole/icons/icons8-search-24.png"))); // NOI18N
        jButton6.setText("Rechrcher");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton6);
        jButton6.setBounds(420, 460, 140, 50);

        jScrollPane8.setViewportView(txtrecherche);

        getContentPane().add(jScrollPane8);
        jScrollPane8.setBounds(260, 460, 130, 40);

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ecole/icons/gestion.jpg"))); // NOI18N
        getContentPane().add(jLabel7);
        jLabel7.setBounds(0, 0, 760, 530);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    //la méthode pour modifier
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        try{
        if(JOptionPane.showConfirmDialog(null, "Confirmer la modification", "modification",
                JOptionPane.YES_NO_OPTION) == JOptionPane.OK_OPTION){
        stm.executeUpdate("UPDATE professeur SET Nom='"+txtnom.getText()+"',Prenom='"+txtprenom.getText()+
                "',matiere='"+txtmatiere.getText()+"',niveau='"+txtniv.getText()+"',start='"+txtstart.getText()+ 
                "' WHERE id= "+txtid.getText());
                afficher();
        }
        }catch (Exception e){JOptionPane.showMessageDialog(null,"erreur de Modification !!!!"+e.getMessage());
        System.err.println(e);}
    }//GEN-LAST:event_jButton2ActionPerformed

    //methode pour actualiser le tableau 
    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        afficher();
    }//GEN-LAST:event_jButton3ActionPerformed

    
    //méhod pour supprimer un professeur
    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        try{
        if(JOptionPane.showConfirmDialog(null, "Attention ! Vous allez supprimer un professeur, est ce que vous etes sure?",
                "Suprimmer professeur", JOptionPane.YES_NO_OPTION)==JOptionPane.OK_OPTION)
            if(txtid.getText().length() !=0){
            stm.executeUpdate("Delete From professeur where id= "+txtid.getText());
            afficher();
            }
            else {JOptionPane.showMessageDialog(null, "veuillez remplire le champ id !");}
        }catch(Exception e){JOptionPane.showMessageDialog(null, "Erreur de suppression\n"+e.getMessage());}
    }//GEN-LAST:event_jButton4ActionPerformed

    //la méthode pour ajouter un prof à la base
    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        String id=txtid.getText();
        String nom=txtnom.getText();
        String prenom=txtprenom.getText();
        String matiere=txtmatiere.getText();
        String niveau=txtniv.getText();
        String debut=txtstart.getText();
        String requete1 = "select * from professeur where Nom ='"+nom+"' and Prenom='"+prenom+"' and matiere='"+matiere+"'";
        String requete = "insert into professeur(id, Nom, Prenom, matiere, niveau, start)VALUES('"+id+"','"+
                nom+"','"+prenom+"','"+matiere+"','"+niveau+"','"+debut+"')";
        try{
            
            
            model.setRowCount(0);//pour vider la liste des etudiants
        
            ResultSet result = stm.executeQuery(requete1);
        if (result.next()){
            JOptionPane.showMessageDialog(null, "l'enseignat exsiste déjà");
        } else {
            stm.executeUpdate(requete);
           JOptionPane.showMessageDialog(null, "l'enseignant est bien ajouter");
           txtid.setText("");
           txtnom.setText("");
           txtprenom.setText("");
           txtmatiere.setText("");
           txtniv.setText(""); 
           txtstart.setText("");
        }
            
        
        afficher();
       
        
        }catch(Exception ex){JOptionPane.showMessageDialog(null,"l'id est déja attribué"+ex.getMessage());}
    }//GEN-LAST:event_jButton5ActionPerformed

    //méthode menu principale
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        PrincipaleProf princi = new PrincipaleProf();
        this.setVisible(false);
        princi.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void tbleMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbleMouseClicked
        // TODO add your handling code here:
         try{
        int i=tble.getSelectedRow();deplace(i);
        }catch(Exception e){JOptionPane.showMessageDialog(null, "erreur de deplacement"+e.getLocalizedMessage());}
    }//GEN-LAST:event_tbleMouseClicked

    //méthode pour rechercher un professeur
    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        try{
        model.setRowCount(0);//pour vider la liste des etudiants
        {
            Rs = stm.executeQuery("Select * From professeur where Nom = '"+txtrecherche.getText()+"'");
        }while (Rs.next()){
        Object [] professeur={Rs.getInt(1),Rs.getString(2),Rs.getString(3),Rs.getString(4),Rs.getString(5),Rs.getString(6)};
        model.addRow(professeur);
        }if(model.getRowCount()==0){JOptionPane.showMessageDialog(null, "il y a aucun professeur avec ce Nom de famille");
        }else {int i=0;
        deplace(i);
        }
        }catch (Exception e){System.err.println(e);
        JOptionPane.showMessageDialog(null,e.getMessage());
        }
    }//GEN-LAST:event_jButton6ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Professeur.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Professeur.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Professeur.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Professeur.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Professeur().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JTable tble;
    private javax.swing.JTextPane txtid;
    private javax.swing.JTextPane txtmatiere;
    private javax.swing.JTextPane txtniv;
    private javax.swing.JTextPane txtnom;
    private javax.swing.JTextPane txtprenom;
    private javax.swing.JTextPane txtrecherche;
    private javax.swing.JTextPane txtstart;
    // End of variables declaration//GEN-END:variables
}
